apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket
  template:
    metadata:
      labels:
        app: ticket
    spec:
      containers:
        - name: ticket
          image: vivvk/ticket
          env:
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MONGO_URI
              value: "mongodb://ticket-mongo-srv:27017/tickets"
            - name: JWT_KEY # We are creating.
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY # This is different, we are getting from the secret...
          imagePullPolicy: Never
          volumeMounts:
            - name: tickets-data
              mountPath: /app/data # This is where your app writes persistent data
      volumes:
        - name: tickets-data
          persistentVolumeClaim:
            claimName: tickets-data-pvc
--- # below service will create ClusterIP service to communicate between the pods
apiVersion: v1
kind: Service
metadata:
  name: ticket-srv
spec:
  selector:
    app: ticket
  ports:
    - name: ticket
      protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tickets-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Adjust size based on your needs
